//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal.JobsIE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.jobs.ie/webservices/", ConfigurationName="JobsIE.JobWSSoap")]
    public interface JobWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetEmployerStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.EmployerStatsResponse GetEmployerStats(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetEmployerStats", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.EmployerStatsResponse> GetEmployerStatsAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/ExpireJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.ExpireJobsResponse ExpireJob(string login, string password, int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/ExpireJob", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.ExpireJobsResponse> ExpireJobAsync(string login, string password, int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/PostJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.CreateJobResponse PostJob(string login, string password, StudentPortal.JobsIE.Job job);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/PostJob", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.CreateJobResponse> PostJobAsync(string login, string password, StudentPortal.JobsIE.Job job);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/RefreshJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.RefreshResponse RefreshJob(string login, string password, int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/RefreshJob", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.RefreshResponse> RefreshJobAsync(string login, string password, int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/UpdateJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.UpdateResponse UpdateJob(string login, string password, StudentPortal.JobsIE.Job job);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/UpdateJob", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.UpdateResponse> UpdateJobAsync(string login, string password, StudentPortal.JobsIE.Job job);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/SearchJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.SearchJobsResponse SearchJobs(StudentPortal.JobsIE.SearchJobsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/SearchJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.SearchJobsResponse> SearchJobsAsync(StudentPortal.JobsIE.SearchJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetJobDisplay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.JobDisplay GetJobDisplay(int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetJobDisplay", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.JobDisplay> GetJobDisplayAsync(int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/AddApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        bool AddApplication(StudentPortal.JobsIE.ApplicationData application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/AddApplication", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddApplicationAsync(StudentPortal.JobsIE.ApplicationData application);
        
        // CODEGEN: Parameter 'GetJobCategoriesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetJobCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.GetJobCategoriesResponse GetJobCategories(StudentPortal.JobsIE.GetJobCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetJobCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetJobCategoriesResponse> GetJobCategoriesAsync(StudentPortal.JobsIE.GetJobCategoriesRequest request);
        
        // CODEGEN: Parameter 'GetIndustriesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetIndustries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.GetIndustriesResponse GetIndustries(StudentPortal.JobsIE.GetIndustriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetIndustries", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetIndustriesResponse> GetIndustriesAsync(StudentPortal.JobsIE.GetIndustriesRequest request);
        
        // CODEGEN: Parameter 'GetJobRegionsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetJobRegions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.GetJobRegionsResponse GetJobRegions(StudentPortal.JobsIE.GetJobRegionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetJobRegions", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetJobRegionsResponse> GetJobRegionsAsync(StudentPortal.JobsIE.GetJobRegionsRequest request);
        
        // CODEGEN: Parameter 'GetCountriesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.GetCountriesResponse GetCountries(StudentPortal.JobsIE.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetCountriesResponse> GetCountriesAsync(StudentPortal.JobsIE.GetCountriesRequest request);
        
        // CODEGEN: Parameter 'GetAddressRegionsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetAddressRegions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JobServiceBaseResponse))]
        StudentPortal.JobsIE.GetAddressRegionsResponse GetAddressRegions(StudentPortal.JobsIE.GetAddressRegionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jobs.ie/webservices/GetAddressRegions", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetAddressRegionsResponse> GetAddressRegionsAsync(StudentPortal.JobsIE.GetAddressRegionsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class EmployerStatsResponse : JobServiceBaseResponse {
        
        private EmployerStats employerStatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EmployerStats EmployerStats {
            get {
                return this.employerStatsField;
            }
            set {
                this.employerStatsField = value;
                this.RaisePropertyChanged("EmployerStats");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class EmployerStats : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int employerIdField;
        
        private int activeJobCountField;
        
        private int totalJobCountField;
        
        private int activeAdvertLimitField;
        
        private bool isSubscriptionEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EmployerId {
            get {
                return this.employerIdField;
            }
            set {
                this.employerIdField = value;
                this.RaisePropertyChanged("EmployerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ActiveJobCount {
            get {
                return this.activeJobCountField;
            }
            set {
                this.activeJobCountField = value;
                this.RaisePropertyChanged("ActiveJobCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TotalJobCount {
            get {
                return this.totalJobCountField;
            }
            set {
                this.totalJobCountField = value;
                this.RaisePropertyChanged("TotalJobCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ActiveAdvertLimit {
            get {
                return this.activeAdvertLimitField;
            }
            set {
                this.activeAdvertLimitField = value;
                this.RaisePropertyChanged("ActiveAdvertLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsSubscriptionEnabled {
            get {
                return this.isSubscriptionEnabledField;
            }
            set {
                this.isSubscriptionEnabledField = value;
                this.RaisePropertyChanged("IsSubscriptionEnabled");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class AddressRegion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class Country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobRegion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class Industry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class ApplicationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coverNoteField;
        
        private string nameField;
        
        private string phoneField;
        
        private string emailField;
        
        private string answer1Field;
        
        private string answer2Field;
        
        private string answer3Field;
        
        private int jobIdField;
        
        private string cVFileNameField;
        
        private string cVFileTypeField;
        
        private byte[] cVFileDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CoverNote {
            get {
                return this.coverNoteField;
            }
            set {
                this.coverNoteField = value;
                this.RaisePropertyChanged("CoverNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Answer1 {
            get {
                return this.answer1Field;
            }
            set {
                this.answer1Field = value;
                this.RaisePropertyChanged("Answer1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Answer2 {
            get {
                return this.answer2Field;
            }
            set {
                this.answer2Field = value;
                this.RaisePropertyChanged("Answer2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Answer3 {
            get {
                return this.answer3Field;
            }
            set {
                this.answer3Field = value;
                this.RaisePropertyChanged("Answer3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("JobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CVFileName {
            get {
                return this.cVFileNameField;
            }
            set {
                this.cVFileNameField = value;
                this.RaisePropertyChanged("CVFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CVFileType {
            get {
                return this.cVFileTypeField;
            }
            set {
                this.cVFileTypeField = value;
                this.RaisePropertyChanged("CVFileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=10)]
        public byte[] CVFileData {
            get {
                return this.cVFileDataField;
            }
            set {
                this.cVFileDataField = value;
                this.RaisePropertyChanged("CVFileData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobDisplay : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int employerIdField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string htmlDescriptionField;
        
        private string locationField;
        
        private string paymentField;
        
        private string referenceField;
        
        private System.DateTime modifiedDTField;
        
        private System.DateTime createdDTField;
        
        private string applicationURLField;
        
        private string question1Field;
        
        private string question2Field;
        
        private string question3Field;
        
        private bool isFullTimeField;
        
        private bool isPartTimeField;
        
        private bool isPermanentField;
        
        private bool isContractField;
        
        private bool hasLogoField;
        
        private string homepageUrlField;
        
        private string companyField;
        
        private string addressField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        private string contactField;
        
        private string[] categoryNamesField;
        
        private string[] regionNamesField;
        
        private int[] categoryIdsField;
        
        private int[] regionIdsField;
        
        private bool isContactHiddenField;
        
        private bool isCompanyNameHiddenField;
        
        private bool isEmailHiddenField;
        
        private bool isPhoneHiddenField;
        
        private bool isFaxHiddenField;
        
        private bool isAddressHiddenField;
        
        private bool isHomePageHiddenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EmployerId {
            get {
                return this.employerIdField;
            }
            set {
                this.employerIdField = value;
                this.RaisePropertyChanged("EmployerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HtmlDescription {
            get {
                return this.htmlDescriptionField;
            }
            set {
                this.htmlDescriptionField = value;
                this.RaisePropertyChanged("HtmlDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("Payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime ModifiedDT {
            get {
                return this.modifiedDTField;
            }
            set {
                this.modifiedDTField = value;
                this.RaisePropertyChanged("ModifiedDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime CreatedDT {
            get {
                return this.createdDTField;
            }
            set {
                this.createdDTField = value;
                this.RaisePropertyChanged("CreatedDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ApplicationURL {
            get {
                return this.applicationURLField;
            }
            set {
                this.applicationURLField = value;
                this.RaisePropertyChanged("ApplicationURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Question1 {
            get {
                return this.question1Field;
            }
            set {
                this.question1Field = value;
                this.RaisePropertyChanged("Question1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Question2 {
            get {
                return this.question2Field;
            }
            set {
                this.question2Field = value;
                this.RaisePropertyChanged("Question2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Question3 {
            get {
                return this.question3Field;
            }
            set {
                this.question3Field = value;
                this.RaisePropertyChanged("Question3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsFullTime {
            get {
                return this.isFullTimeField;
            }
            set {
                this.isFullTimeField = value;
                this.RaisePropertyChanged("IsFullTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsPartTime {
            get {
                return this.isPartTimeField;
            }
            set {
                this.isPartTimeField = value;
                this.RaisePropertyChanged("IsPartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsPermanent {
            get {
                return this.isPermanentField;
            }
            set {
                this.isPermanentField = value;
                this.RaisePropertyChanged("IsPermanent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsContract {
            get {
                return this.isContractField;
            }
            set {
                this.isContractField = value;
                this.RaisePropertyChanged("IsContract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool HasLogo {
            get {
                return this.hasLogoField;
            }
            set {
                this.hasLogoField = value;
                this.RaisePropertyChanged("HasLogo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string HomepageUrl {
            get {
                return this.homepageUrlField;
            }
            set {
                this.homepageUrlField = value;
                this.RaisePropertyChanged("HomepageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        public string[] CategoryNames {
            get {
                return this.categoryNamesField;
            }
            set {
                this.categoryNamesField = value;
                this.RaisePropertyChanged("CategoryNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        public string[] RegionNames {
            get {
                return this.regionNamesField;
            }
            set {
                this.regionNamesField = value;
                this.RaisePropertyChanged("RegionNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=28)]
        public int[] CategoryIds {
            get {
                return this.categoryIdsField;
            }
            set {
                this.categoryIdsField = value;
                this.RaisePropertyChanged("CategoryIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=29)]
        public int[] RegionIds {
            get {
                return this.regionIdsField;
            }
            set {
                this.regionIdsField = value;
                this.RaisePropertyChanged("RegionIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool IsContactHidden {
            get {
                return this.isContactHiddenField;
            }
            set {
                this.isContactHiddenField = value;
                this.RaisePropertyChanged("IsContactHidden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool IsCompanyNameHidden {
            get {
                return this.isCompanyNameHiddenField;
            }
            set {
                this.isCompanyNameHiddenField = value;
                this.RaisePropertyChanged("IsCompanyNameHidden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public bool IsEmailHidden {
            get {
                return this.isEmailHiddenField;
            }
            set {
                this.isEmailHiddenField = value;
                this.RaisePropertyChanged("IsEmailHidden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool IsPhoneHidden {
            get {
                return this.isPhoneHiddenField;
            }
            set {
                this.isPhoneHiddenField = value;
                this.RaisePropertyChanged("IsPhoneHidden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool IsFaxHidden {
            get {
                return this.isFaxHiddenField;
            }
            set {
                this.isFaxHiddenField = value;
                this.RaisePropertyChanged("IsFaxHidden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public bool IsAddressHidden {
            get {
                return this.isAddressHiddenField;
            }
            set {
                this.isAddressHiddenField = value;
                this.RaisePropertyChanged("IsAddressHidden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public bool IsHomePageHidden {
            get {
                return this.isHomePageHiddenField;
            }
            set {
                this.isHomePageHiddenField = value;
                this.RaisePropertyChanged("IsHomePageHidden");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobListItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime createdDTField;
        
        private string titleField;
        
        private string companyField;
        
        private string locationField;
        
        private int employerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CreatedDT {
            get {
                return this.createdDTField;
            }
            set {
                this.createdDTField = value;
                this.RaisePropertyChanged("CreatedDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int EmployerId {
            get {
                return this.employerIdField;
            }
            set {
                this.employerIdField = value;
                this.RaisePropertyChanged("EmployerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class Job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        private string paymentField;
        
        private string locationField;
        
        private string descriptionField;
        
        private string htmlDescriptionField;
        
        private bool isFullTimeField;
        
        private bool isPartTimeField;
        
        private bool isPermanentField;
        
        private bool isContractField;
        
        private string question1Field;
        
        private string question2Field;
        
        private string question3Field;
        
        private string applicationURLField;
        
        private string[] contactEmailsField;
        
        private System.DateTime expiryDTField;
        
        private System.DateTime createdDTField;
        
        private System.DateTime modifiedDTField;
        
        private string referenceField;
        
        private int[] categoryIdsField;
        
        private int[] regionIdsField;
        
        private int slotTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("Payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HtmlDescription {
            get {
                return this.htmlDescriptionField;
            }
            set {
                this.htmlDescriptionField = value;
                this.RaisePropertyChanged("HtmlDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsFullTime {
            get {
                return this.isFullTimeField;
            }
            set {
                this.isFullTimeField = value;
                this.RaisePropertyChanged("IsFullTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsPartTime {
            get {
                return this.isPartTimeField;
            }
            set {
                this.isPartTimeField = value;
                this.RaisePropertyChanged("IsPartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsPermanent {
            get {
                return this.isPermanentField;
            }
            set {
                this.isPermanentField = value;
                this.RaisePropertyChanged("IsPermanent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsContract {
            get {
                return this.isContractField;
            }
            set {
                this.isContractField = value;
                this.RaisePropertyChanged("IsContract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Question1 {
            get {
                return this.question1Field;
            }
            set {
                this.question1Field = value;
                this.RaisePropertyChanged("Question1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Question2 {
            get {
                return this.question2Field;
            }
            set {
                this.question2Field = value;
                this.RaisePropertyChanged("Question2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Question3 {
            get {
                return this.question3Field;
            }
            set {
                this.question3Field = value;
                this.RaisePropertyChanged("Question3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ApplicationURL {
            get {
                return this.applicationURLField;
            }
            set {
                this.applicationURLField = value;
                this.RaisePropertyChanged("ApplicationURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public string[] ContactEmails {
            get {
                return this.contactEmailsField;
            }
            set {
                this.contactEmailsField = value;
                this.RaisePropertyChanged("ContactEmails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime ExpiryDT {
            get {
                return this.expiryDTField;
            }
            set {
                this.expiryDTField = value;
                this.RaisePropertyChanged("ExpiryDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime CreatedDT {
            get {
                return this.createdDTField;
            }
            set {
                this.createdDTField = value;
                this.RaisePropertyChanged("CreatedDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime ModifiedDT {
            get {
                return this.modifiedDTField;
            }
            set {
                this.modifiedDTField = value;
                this.RaisePropertyChanged("ModifiedDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        public int[] CategoryIds {
            get {
                return this.categoryIdsField;
            }
            set {
                this.categoryIdsField = value;
                this.RaisePropertyChanged("CategoryIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public int[] RegionIds {
            get {
                return this.regionIdsField;
            }
            set {
                this.regionIdsField = value;
                this.RaisePropertyChanged("RegionIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int SlotType {
            get {
                return this.slotTypeField;
            }
            set {
                this.slotTypeField = value;
                this.RaisePropertyChanged("SlotType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SlotBalanceAgencySlots))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SlotBalanceAgencyCredits))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SlotBalanceCorporate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public abstract partial class SlotBalance : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class SlotBalanceAgencySlots : SlotBalance {
        
        private int totalSlotsField;
        
        private int slotsInUseField;
        
        private int freeSlotsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalSlots {
            get {
                return this.totalSlotsField;
            }
            set {
                this.totalSlotsField = value;
                this.RaisePropertyChanged("TotalSlots");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SlotsInUse {
            get {
                return this.slotsInUseField;
            }
            set {
                this.slotsInUseField = value;
                this.RaisePropertyChanged("SlotsInUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int FreeSlots {
            get {
                return this.freeSlotsField;
            }
            set {
                this.freeSlotsField = value;
                this.RaisePropertyChanged("FreeSlots");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class SlotBalanceAgencyCredits : SlotBalance {
        
        private int totalCreditsField;
        
        private int creditsRemainingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalCredits {
            get {
                return this.totalCreditsField;
            }
            set {
                this.totalCreditsField = value;
                this.RaisePropertyChanged("TotalCredits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
                this.RaisePropertyChanged("CreditsRemaining");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class SlotBalanceCorporate : SlotBalance {
        
        private int standardSlotsFreeField;
        
        private int standardSlotsInUseField;
        
        private int professionalSlotsFreeField;
        
        private int professionalSlotsInUseField;
        
        private int premiumSlotsFreeField;
        
        private int premiumSlotsInUseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StandardSlotsFree {
            get {
                return this.standardSlotsFreeField;
            }
            set {
                this.standardSlotsFreeField = value;
                this.RaisePropertyChanged("StandardSlotsFree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int StandardSlotsInUse {
            get {
                return this.standardSlotsInUseField;
            }
            set {
                this.standardSlotsInUseField = value;
                this.RaisePropertyChanged("StandardSlotsInUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ProfessionalSlotsFree {
            get {
                return this.professionalSlotsFreeField;
            }
            set {
                this.professionalSlotsFreeField = value;
                this.RaisePropertyChanged("ProfessionalSlotsFree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ProfessionalSlotsInUse {
            get {
                return this.professionalSlotsInUseField;
            }
            set {
                this.professionalSlotsInUseField = value;
                this.RaisePropertyChanged("ProfessionalSlotsInUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PremiumSlotsFree {
            get {
                return this.premiumSlotsFreeField;
            }
            set {
                this.premiumSlotsFreeField = value;
                this.RaisePropertyChanged("PremiumSlotsFree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int PremiumSlotsInUse {
            get {
                return this.premiumSlotsInUseField;
            }
            set {
                this.premiumSlotsInUseField = value;
                this.RaisePropertyChanged("PremiumSlotsInUse");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RefreshResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateJobResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpireJobsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployerStatsResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public abstract partial class JobServiceBaseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private SlotBalance balanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SlotBalance Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class UpdateResponse : JobServiceBaseResponse {
        
        private int updateCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UpdateCount {
            get {
                return this.updateCountField;
            }
            set {
                this.updateCountField = value;
                this.RaisePropertyChanged("UpdateCount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class RefreshResponse : JobServiceBaseResponse {
        
        private int refreshCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RefreshCount {
            get {
                return this.refreshCountField;
            }
            set {
                this.refreshCountField = value;
                this.RaisePropertyChanged("RefreshCount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class CreateJobResponse : JobServiceBaseResponse {
        
        private int jobIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("JobId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class ExpireJobsResponse : JobServiceBaseResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public enum JobDuration {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        Permanent,
        
        /// <remarks/>
        Contract,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public enum JobHours {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        FullTime,
        
        /// <remarks/>
        PartTime,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchJobs", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class SearchJobsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=0)]
        public int[] employerIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=1)]
        public int[] jobCategoryIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=2)]
        public int[] regionIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=3)]
        public bool excludeAgencies;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=4)]
        public int[] industryIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=5)]
        public StudentPortal.JobsIE.JobDuration jobType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=6)]
        public StudentPortal.JobsIE.JobHours jobHours;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=7)]
        public string keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=8)]
        public System.DateTime fromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=9)]
        public System.DateTime toDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=10)]
        public int startRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=11)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=12)]
        public string key;
        
        public SearchJobsRequest() {
        }
        
        public SearchJobsRequest(int[] employerIds, int[] jobCategoryIds, int[] regionIds, bool excludeAgencies, int[] industryIds, StudentPortal.JobsIE.JobDuration jobType, StudentPortal.JobsIE.JobHours jobHours, string keywords, System.DateTime fromDate, System.DateTime toDate, int startRecord, int pageSize, string key) {
            this.employerIds = employerIds;
            this.jobCategoryIds = jobCategoryIds;
            this.regionIds = regionIds;
            this.excludeAgencies = excludeAgencies;
            this.industryIds = industryIds;
            this.jobType = jobType;
            this.jobHours = jobHours;
            this.keywords = keywords;
            this.fromDate = fromDate;
            this.toDate = toDate;
            this.startRecord = startRecord;
            this.pageSize = pageSize;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchJobsResponse", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class SearchJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StudentPortal.JobsIE.JobListItem[] SearchJobsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=1)]
        public int recordCount;
        
        public SearchJobsResponse() {
        }
        
        public SearchJobsResponse(StudentPortal.JobsIE.JobListItem[] SearchJobsResult, int recordCount) {
            this.SearchJobsResult = SearchJobsResult;
            this.recordCount = recordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobCategories", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetJobCategoriesRequest {
        
        public GetJobCategoriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobCategoriesResponse", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetJobCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StudentPortal.JobsIE.JobCategory[] GetJobCategoriesResult;
        
        public GetJobCategoriesResponse() {
        }
        
        public GetJobCategoriesResponse(StudentPortal.JobsIE.JobCategory[] GetJobCategoriesResult) {
            this.GetJobCategoriesResult = GetJobCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIndustries", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetIndustriesRequest {
        
        public GetIndustriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIndustriesResponse", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetIndustriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StudentPortal.JobsIE.Industry[] GetIndustriesResult;
        
        public GetIndustriesResponse() {
        }
        
        public GetIndustriesResponse(StudentPortal.JobsIE.Industry[] GetIndustriesResult) {
            this.GetIndustriesResult = GetIndustriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobRegions", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetJobRegionsRequest {
        
        public GetJobRegionsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobRegionsResponse", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetJobRegionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StudentPortal.JobsIE.JobRegion[] GetJobRegionsResult;
        
        public GetJobRegionsResponse() {
        }
        
        public GetJobRegionsResponse(StudentPortal.JobsIE.JobRegion[] GetJobRegionsResult) {
            this.GetJobRegionsResult = GetJobRegionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountries", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetCountriesRequest {
        
        public GetCountriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountriesResponse", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StudentPortal.JobsIE.Country[] GetCountriesResult;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(StudentPortal.JobsIE.Country[] GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressRegions", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetAddressRegionsRequest {
        
        public GetAddressRegionsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressRegionsResponse", WrapperNamespace="http://www.jobs.ie/webservices/", IsWrapped=true)]
    public partial class GetAddressRegionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jobs.ie/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StudentPortal.JobsIE.AddressRegion[] GetAddressRegionsResult;
        
        public GetAddressRegionsResponse() {
        }
        
        public GetAddressRegionsResponse(StudentPortal.JobsIE.AddressRegion[] GetAddressRegionsResult) {
            this.GetAddressRegionsResult = GetAddressRegionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JobWSSoapChannel : StudentPortal.JobsIE.JobWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobWSSoapClient : System.ServiceModel.ClientBase<StudentPortal.JobsIE.JobWSSoap>, StudentPortal.JobsIE.JobWSSoap {
        
        public JobWSSoapClient() {
        }
        
        public JobWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudentPortal.JobsIE.EmployerStatsResponse GetEmployerStats(string login, string password) {
            return base.Channel.GetEmployerStats(login, password);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.EmployerStatsResponse> GetEmployerStatsAsync(string login, string password) {
            return base.Channel.GetEmployerStatsAsync(login, password);
        }
        
        public StudentPortal.JobsIE.ExpireJobsResponse ExpireJob(string login, string password, int jobId) {
            return base.Channel.ExpireJob(login, password, jobId);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.ExpireJobsResponse> ExpireJobAsync(string login, string password, int jobId) {
            return base.Channel.ExpireJobAsync(login, password, jobId);
        }
        
        public StudentPortal.JobsIE.CreateJobResponse PostJob(string login, string password, StudentPortal.JobsIE.Job job) {
            return base.Channel.PostJob(login, password, job);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.CreateJobResponse> PostJobAsync(string login, string password, StudentPortal.JobsIE.Job job) {
            return base.Channel.PostJobAsync(login, password, job);
        }
        
        public StudentPortal.JobsIE.RefreshResponse RefreshJob(string login, string password, int jobId) {
            return base.Channel.RefreshJob(login, password, jobId);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.RefreshResponse> RefreshJobAsync(string login, string password, int jobId) {
            return base.Channel.RefreshJobAsync(login, password, jobId);
        }
        
        public StudentPortal.JobsIE.UpdateResponse UpdateJob(string login, string password, StudentPortal.JobsIE.Job job) {
            return base.Channel.UpdateJob(login, password, job);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.UpdateResponse> UpdateJobAsync(string login, string password, StudentPortal.JobsIE.Job job) {
            return base.Channel.UpdateJobAsync(login, password, job);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentPortal.JobsIE.SearchJobsResponse StudentPortal.JobsIE.JobWSSoap.SearchJobs(StudentPortal.JobsIE.SearchJobsRequest request) {
            return base.Channel.SearchJobs(request);
        }
        
        public StudentPortal.JobsIE.JobListItem[] SearchJobs(int[] employerIds, int[] jobCategoryIds, int[] regionIds, bool excludeAgencies, int[] industryIds, StudentPortal.JobsIE.JobDuration jobType, StudentPortal.JobsIE.JobHours jobHours, string keywords, System.DateTime fromDate, System.DateTime toDate, int startRecord, int pageSize, string key, out int recordCount) {
            StudentPortal.JobsIE.SearchJobsRequest inValue = new StudentPortal.JobsIE.SearchJobsRequest();
            inValue.employerIds = employerIds;
            inValue.jobCategoryIds = jobCategoryIds;
            inValue.regionIds = regionIds;
            inValue.excludeAgencies = excludeAgencies;
            inValue.industryIds = industryIds;
            inValue.jobType = jobType;
            inValue.jobHours = jobHours;
            inValue.keywords = keywords;
            inValue.fromDate = fromDate;
            inValue.toDate = toDate;
            inValue.startRecord = startRecord;
            inValue.pageSize = pageSize;
            inValue.key = key;
            StudentPortal.JobsIE.SearchJobsResponse retVal = ((StudentPortal.JobsIE.JobWSSoap)(this)).SearchJobs(inValue);
            recordCount = retVal.recordCount;
            return retVal.SearchJobsResult;
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.SearchJobsResponse> SearchJobsAsync(StudentPortal.JobsIE.SearchJobsRequest request) {
            return base.Channel.SearchJobsAsync(request);
        }
        
        public StudentPortal.JobsIE.JobDisplay GetJobDisplay(int jobId) {
            return base.Channel.GetJobDisplay(jobId);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.JobDisplay> GetJobDisplayAsync(int jobId) {
            return base.Channel.GetJobDisplayAsync(jobId);
        }
        
        public bool AddApplication(StudentPortal.JobsIE.ApplicationData application) {
            return base.Channel.AddApplication(application);
        }
        
        public System.Threading.Tasks.Task<bool> AddApplicationAsync(StudentPortal.JobsIE.ApplicationData application) {
            return base.Channel.AddApplicationAsync(application);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentPortal.JobsIE.GetJobCategoriesResponse StudentPortal.JobsIE.JobWSSoap.GetJobCategories(StudentPortal.JobsIE.GetJobCategoriesRequest request) {
            return base.Channel.GetJobCategories(request);
        }
        
        public StudentPortal.JobsIE.JobCategory[] GetJobCategories() {
            StudentPortal.JobsIE.GetJobCategoriesRequest inValue = new StudentPortal.JobsIE.GetJobCategoriesRequest();
            StudentPortal.JobsIE.GetJobCategoriesResponse retVal = ((StudentPortal.JobsIE.JobWSSoap)(this)).GetJobCategories(inValue);
            return retVal.GetJobCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetJobCategoriesResponse> StudentPortal.JobsIE.JobWSSoap.GetJobCategoriesAsync(StudentPortal.JobsIE.GetJobCategoriesRequest request) {
            return base.Channel.GetJobCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.GetJobCategoriesResponse> GetJobCategoriesAsync() {
            StudentPortal.JobsIE.GetJobCategoriesRequest inValue = new StudentPortal.JobsIE.GetJobCategoriesRequest();
            return ((StudentPortal.JobsIE.JobWSSoap)(this)).GetJobCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentPortal.JobsIE.GetIndustriesResponse StudentPortal.JobsIE.JobWSSoap.GetIndustries(StudentPortal.JobsIE.GetIndustriesRequest request) {
            return base.Channel.GetIndustries(request);
        }
        
        public StudentPortal.JobsIE.Industry[] GetIndustries() {
            StudentPortal.JobsIE.GetIndustriesRequest inValue = new StudentPortal.JobsIE.GetIndustriesRequest();
            StudentPortal.JobsIE.GetIndustriesResponse retVal = ((StudentPortal.JobsIE.JobWSSoap)(this)).GetIndustries(inValue);
            return retVal.GetIndustriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetIndustriesResponse> StudentPortal.JobsIE.JobWSSoap.GetIndustriesAsync(StudentPortal.JobsIE.GetIndustriesRequest request) {
            return base.Channel.GetIndustriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.GetIndustriesResponse> GetIndustriesAsync() {
            StudentPortal.JobsIE.GetIndustriesRequest inValue = new StudentPortal.JobsIE.GetIndustriesRequest();
            return ((StudentPortal.JobsIE.JobWSSoap)(this)).GetIndustriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentPortal.JobsIE.GetJobRegionsResponse StudentPortal.JobsIE.JobWSSoap.GetJobRegions(StudentPortal.JobsIE.GetJobRegionsRequest request) {
            return base.Channel.GetJobRegions(request);
        }
        
        public StudentPortal.JobsIE.JobRegion[] GetJobRegions() {
            StudentPortal.JobsIE.GetJobRegionsRequest inValue = new StudentPortal.JobsIE.GetJobRegionsRequest();
            StudentPortal.JobsIE.GetJobRegionsResponse retVal = ((StudentPortal.JobsIE.JobWSSoap)(this)).GetJobRegions(inValue);
            return retVal.GetJobRegionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetJobRegionsResponse> StudentPortal.JobsIE.JobWSSoap.GetJobRegionsAsync(StudentPortal.JobsIE.GetJobRegionsRequest request) {
            return base.Channel.GetJobRegionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.GetJobRegionsResponse> GetJobRegionsAsync() {
            StudentPortal.JobsIE.GetJobRegionsRequest inValue = new StudentPortal.JobsIE.GetJobRegionsRequest();
            return ((StudentPortal.JobsIE.JobWSSoap)(this)).GetJobRegionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentPortal.JobsIE.GetCountriesResponse StudentPortal.JobsIE.JobWSSoap.GetCountries(StudentPortal.JobsIE.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public StudentPortal.JobsIE.Country[] GetCountries() {
            StudentPortal.JobsIE.GetCountriesRequest inValue = new StudentPortal.JobsIE.GetCountriesRequest();
            StudentPortal.JobsIE.GetCountriesResponse retVal = ((StudentPortal.JobsIE.JobWSSoap)(this)).GetCountries(inValue);
            return retVal.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetCountriesResponse> StudentPortal.JobsIE.JobWSSoap.GetCountriesAsync(StudentPortal.JobsIE.GetCountriesRequest request) {
            return base.Channel.GetCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.GetCountriesResponse> GetCountriesAsync() {
            StudentPortal.JobsIE.GetCountriesRequest inValue = new StudentPortal.JobsIE.GetCountriesRequest();
            return ((StudentPortal.JobsIE.JobWSSoap)(this)).GetCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentPortal.JobsIE.GetAddressRegionsResponse StudentPortal.JobsIE.JobWSSoap.GetAddressRegions(StudentPortal.JobsIE.GetAddressRegionsRequest request) {
            return base.Channel.GetAddressRegions(request);
        }
        
        public StudentPortal.JobsIE.AddressRegion[] GetAddressRegions() {
            StudentPortal.JobsIE.GetAddressRegionsRequest inValue = new StudentPortal.JobsIE.GetAddressRegionsRequest();
            StudentPortal.JobsIE.GetAddressRegionsResponse retVal = ((StudentPortal.JobsIE.JobWSSoap)(this)).GetAddressRegions(inValue);
            return retVal.GetAddressRegionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentPortal.JobsIE.GetAddressRegionsResponse> StudentPortal.JobsIE.JobWSSoap.GetAddressRegionsAsync(StudentPortal.JobsIE.GetAddressRegionsRequest request) {
            return base.Channel.GetAddressRegionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentPortal.JobsIE.GetAddressRegionsResponse> GetAddressRegionsAsync() {
            StudentPortal.JobsIE.GetAddressRegionsRequest inValue = new StudentPortal.JobsIE.GetAddressRegionsRequest();
            return ((StudentPortal.JobsIE.JobWSSoap)(this)).GetAddressRegionsAsync(inValue);
        }
    }
}
