// <auto-generated />
namespace StudentPortalAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Education_Experience : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Education_Experience));
        
        string IMigrationMetadata.Id
        {
            get { return "201805011642593_Education_Experience"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
